/**
 * Mots-clés ajoutés aux opérations de CyberChef, pour les trouver sous le nom
 * qu'on leur donne couramment plutôt que sous leur nom exact.
 *
 * Le cas d'origine : le chiffre de César n'existe pas sous ce nom dans
 * CyberChef, c'est ROT13 (décalage réglable). « Caesar Box Cipher » est un
 * chiffrement par transposition, sans rapport. Qui cherche « caesar » doit
 * trouver les deux.
 *
 * Clé : nom exact de l'opération. Les outils IT-Tools qui ont un équivalent
 * CyberChef héritent de ses mots-clés (voir le registre).
 */
export const OPERATION_KEYWORDS: Record<string, string[]> = {
  'ROT13': ['caesar cipher', 'césar', 'chiffre de césar', 'shift cipher', 'décalage', 'rot'],
  'ROT13 Brute Force': ['caesar', 'césar', 'brute force', 'force brute'],
  'ROT47': ['caesar', 'césar'],
  'ROT8000': ['caesar', 'césar'],
  'Caesar Box Cipher': ['transposition'],
  'Substitute': ['substitution cipher', 'chiffre de substitution'],
  'Rail Fence Cipher Encode': ['zigzag', 'transposition'],
  'Rail Fence Cipher Decode': ['zigzag', 'transposition'],
  'Bacon Cipher Encode': ['baconian'],
  'Bacon Cipher Decode': ['baconian'],
  'Atbash Cipher': ['mirror alphabet', 'alphabet inversé'],
  'XOR': ['xor key', 'clé xor', 'ou exclusif'],
  'XOR Brute Force': ['xor', 'force brute', 'single byte xor'],
  'AES Encrypt': ['rijndael', 'chiffrement symétrique'],
  'AES Decrypt': ['rijndael', 'chiffrement symétrique'],
  'SHA2': ['sha256', 'sha-256', 'sha512', 'sha-512', 'sha224', 'sha384'],
  'SHA1': ['sha-1'],
  'SHA3': ['sha3-256', 'sha3-512'],
  'MD5': ['md-5', 'checksum'],
  'CRC Checksum': ['crc32', 'crc16', 'crc-32'],
  'Bcrypt': ['password hash', 'mot de passe'],
  'Scrypt': ['password hash', 'kdf'],
  'Derive PBKDF2 key': ['pbkdf2', 'kdf', 'password'],
  'JWT Decode': ['json web token', 'bearer'],
  'JWT Sign': ['json web token'],
  'JWT Verify': ['json web token'],
  'To Base64': ['b64', 'base 64'],
  'From Base64': ['b64', 'base 64'],
  'URL Encode': ['percent encoding', 'urlencode', 'encodage pourcent'],
  'URL Decode': ['percent encoding', 'urldecode', 'encodage pourcent'],
  'From HTML Entity': ['html decode', 'unescape html'],
  'To HTML Entity': ['html encode', 'escape html'],
  'Unescape string': ['unescape', 'backslash'],
  'Escape string': ['escape', 'backslash'],
  'From Charcode': ['ascii codes', 'char codes', 'codes ascii'],
  'To Charcode': ['ascii codes', 'char codes', 'codes ascii'],
  'To Hex': ['hexadecimal', 'hexa'],
  'From Hex': ['hexadecimal', 'hexa'],
  'To Hexdump': ['xxd', 'hexdump'],
  'From Hexdump': ['xxd', 'hexdump'],
  'Parse X.509 certificate': ['certificate', 'certificat', 'pem', 'ssl', 'tls'],
  'Parse X.509 CRL': ['certificate', 'certificat', 'revocation'],
  'From UNIX Timestamp': ['epoch', 'timestamp', 'horodatage'],
  'To UNIX Timestamp': ['epoch', 'timestamp', 'horodatage'],
  'Generate UUID': ['guid'],
  'Regular expression': ['regex', 'regexp', 'expression régulière'],
  'Find / Replace': ['sed', 'remplacer', 'rechercher remplacer'],
  'Gunzip': ['gzip', 'decompress', 'décompresser', 'gz'],
  'Gzip': ['compress', 'compresser', 'gz'],
  'Unzip': ['zip', 'decompress', 'extraire archive'],
  'Zip': ['compress', 'archive'],
  'Raw Inflate': ['deflate', 'decompress', 'zlib'],
  'Zlib Inflate': ['deflate', 'decompress'],
  'Entropy': ['entropie', 'shannon', 'randomness'],
  'Strings': ['extract strings', 'chaînes'],
  'Detect File Type': ['magic bytes', 'file signature', 'mime', 'signature de fichier'],
  'Magic': ['auto decode', 'detect encoding', 'détecter', 'identifier'],
  'Defang URL': ['defang', 'ioc'],
  'Extract URLs': ['ioc', 'liens'],
  'Extract IP addresses': ['ioc', 'ip'],
  'Extract email addresses': ['ioc', 'mail'],
  'To Morse Code': ['morse'],
  'From Morse Code': ['morse'],
  'Convert to NATO alphabet': ['alphabet radio', 'alpha bravo'],
  'Parse User Agent': ['user agent', 'navigateur'],
  'Frequency distribution': ['histogram', 'fréquence', 'analyse fréquentielle'],
  'Index of Coincidence': ['ioc', 'kasiski', 'indice de coïncidence'],
  'Vigenère Encode': ['vigenere', 'polyalphabetic'],
  'Vigenère Decode': ['vigenere', 'polyalphabetic'],
  'Affine Cipher Encode': ['affine'],
  'Affine Cipher Decode': ['affine'],
  'Enigma': ['machine enigma', 'wwii'],
  'Diff': ['compare', 'comparer', 'différence'],
  'JSON Beautify': ['json format', 'pretty print', 'indenter'],
  'JSON Minify': ['compact', 'minifier'],
  'To Upper case': ['uppercase', 'majuscules'],
  'To Lower case': ['lowercase', 'minuscules'],
  'Reverse': ['inverser', 'retourner'],
  'Sort': ['trier'],
  'Unique': ['dedupe', 'dédoublonner', 'doublons'],
  'Count occurrences': ['compter'],
  'Remove whitespace': ['espaces', 'trim'],
  'Generate QR Code': ['qr', 'qrcode'],
  'Parse QR Code': ['qr', 'qrcode', 'scanner'],
  'Generate TOTP': ['2fa', 'otp', 'authenticator'],
  'Generate HOTP': ['2fa', 'otp'],
  'Change IP format': ['ip', 'ipv4', 'decimal ip'],
  'Parse IP range': ['cidr', 'subnet', 'sous-réseau'],
  'To Binary': ['binaire', 'bits'],
  'From Binary': ['binaire', 'bits'],
  'To Base': ['radix', 'base conversion'],
  'From Base': ['radix', 'base conversion'],
};
